var Board={width:500,height:500,element:null,grid:null,board:null,polyform:null,hover_poly:null,hover_poly_is_dragging:false,anchor_xy:null,orig_xy:null,is_snapping_on:true,is_puzzling:false,validateCallback:null,id:null};
Board.init=function(){var a=document.getElementById("grid");Board.grid=a.getContext("2d");Board.element=document.getElementById("board");Board.width=Board.element.width;Board.height=Board.element.height;Board.board=Board.element.getContext("2d");Board.element.onmousemove=Board.onMouseMove;Board.element.onmousedown=Board.onMouseDown;Board.element.onmouseup=Board.onMouseUp;Board.element.onmouseout=Board.onMouseOut};
Board.startPuzzling=function(){Board.drawGrid();Board.id=window.setInterval("Board.drawPolyform()",30);Board.is_puzzling=true};Board.stopPuzzling=function(){Board.is_puzzling=false;Board.element.onmousemove=null;Board.element.onmousedown=null;Board.element.onmouseup=null;Board.element.onmouseout=null;Board.element.onmouseleave=null;window.clearInterval(Board.id)};
Board.drawGrid=function(){Board.grid.lineWidth=5;Board.grid.strokeStyle="rgba(220, 220, 220, 1)";Board.grid.strokeRect(0,0,Board.width,Board.height);Board.grid.fillStyle="rgba(220, 220, 220, 0.5)";for(var a=50;a<Board.width;a+=50)Board.grid.fillRect(a-1,0,2,Board.height);for(a=50;a<Board.height;a+=50)Board.grid.fillRect(0,a-1,Board.width,2)};
Board.drawPolyform=function(){Board.clear();for(var a=Board.polyform.polys.length,b=0;b<a;++b)Board.drawPoly(Board.polyform.polys[b]);null!=Board.anchor_xy&&Board.drawAnchorXY()};Board.clear=function(){Board.board.clearRect(0,0,Board.width,Board.height)};
Board.drawPoly=function(a){Board.board.beginPath();Board.board.fillStyle=null!=Board.hover_poly&&a.name===Board.hover_poly.name?"rgba(0, 150, 250, 0.7)":"rgba(10, 100, 200, 0.7)";Board.board.strokeStyle="rgba(10, 100, 250, 0.9)";Board.board.lineCap="round";Board.board.lineJoin="round";Board.board.lineWidth=2;a=a.points;var b=a.length;Board.board.moveTo(a[b-1].x,a[b-1].y);for(var d=0;d<b;++d)Board.board.lineTo(a[d].x,a[d].y);Board.board.stroke();Board.board.fill()};
Board.drawAnchorXY=function(){var a=Board.anchor_xy.x,b=Board.anchor_xy.y;Board.board.beginPath();Board.board.strokeStyle="rgba(110, 110, 110, 0.7)";Board.board.lineWidth=2;Board.board.arc(a,b,9,0,2*Math.PI,true);Board.board.stroke();var d=4.5*Math.sqrt(3);Board.board.beginPath();Board.board.fillStyle="rgba(110, 110, 110, 1)";Board.board.lineWidth=1;Board.board.moveTo(a+9-4.5,b);Board.board.lineTo(a+9+4.5,b);Board.board.lineTo(a+9,b-d);Board.board.moveTo(a-9-4.5,b);Board.board.lineTo(a-9+4.5,b);Board.board.lineTo(a-
9,b+d);Board.board.fill()};Board.getRelativePosition=function(a){a=window.event?window.event:a;if(undefined!=a.layerX&&undefined!=a.layerY)return{x:a.layerX,y:a.layerY};if(undefined!=a.x&&undefined!=a.y)return{x:a.x,y:a.y};return{x:a.offsetX,y:a.offsetY}};
Board.onMouseMove=function(a){if(Board.is_puzzling){a=Board.getRelativePosition(a);if(Board.hover_poly_is_dragging)if(null!=Board.anchor_xy){var b=Board.getPolyCenter(Board.hover_poly),d=Board.calculateTheta(a,b);Board.rotatePoly(Board.hover_poly,b,d)}else{b={x:a.x-Board.orig_xy.x,y:a.y-Board.orig_xy.y};if(b.x!=0||b.y!=0)Board.translatePoly(Board.hover_poly,b)}else Board.calculateHoverAndAnchor(a);Board.orig_xy=a}};
Board.onMouseDown=function(a){if(Board.is_puzzling){Board.orig_xy=Board.getRelativePosition(a);Board.hover_poly_is_dragging=null!=Board.hover_poly}};Board.onMouseUp=function(a){if(Board.is_puzzling){Board.hover_poly_is_dragging&&Board.is_snapping_on&&Board.snapPoly(Board.hover_poly);Board.validatePolyform();Board.hover_poly_is_dragging=false;Board.orig_xy=Board.getRelativePosition(a)}};
Board.onMouseOut=function(){if(Board.is_puzzling){Board.hover_poly=null;Board.hover_poly_is_dragging=false;Board.anchor_xy=null}};Board.getPolyCenter=function(a){for(var b={x:0,y:0},d=0,e=0,c=a.points.length,f=0;f<c;++f){d+=a.points[f].x;e+=a.points[f].y}if(c>0){b.x=d/c;b.y=e/c}return b};
Board.rotatePoly=function(a,b,d){for(var e=a.points.length,c=0;c<e;++c)if(!Board.contains(Math.rotateXY(a.points[c],b,d)))return;for(c=0;c<e;++c)a.points[c]=Math.rotateXY(a.points[c],b,d);Board.anchor_xy=Math.rotateXY(Board.anchor_xy,b,d)};Board.translatePoly=function(a,b){for(var d=a.points.length,e=0;e<d;++e)if(!Board.contains(Math.translateXY(a.points[e],b)))return;for(e=0;e<d;++e)a.points[e]=Math.translateXY(a.points[e],b)};
Board.calculateTheta=function(a,b){var d=Math.atan2(Board.orig_xy.y-b.y,Board.orig_xy.x-b.x),e=Math.atan2(a.y-b.y,a.x-b.x),c=e-d;if(c<0)c=Math.PI+(Math.PI-c);return e>d?-c:c};
Board.calculateHoverAndAnchor=function(a){Board.hover_poly=null;Board.anchor_xy=null;for(var b=Board.polyform.polys.length,d=0;d<b;++d){var e=Board.polyform.polys[d];if(Board.polyContains(e,a))Board.hover_poly=e;for(var c=e.points.length,f=0;f<c;++f)if(Math.distXY(e.points[f],a)<9){Board.anchor_xy=e.points[f];break}if(null!=Board.anchor_xy&&null==Board.hover_poly)Board.hover_poly=e;if(null!=Board.hover_poly)break}};Board.contains=function(a){return a.x>0&&a.x<Board.width&&a.y>0&&a.y<Board.height};
Board.polyContains=function(a,b){for(var d=a.points.length,e=0,c=0,f=d-1;c<d;f=c++){var j=a.points[f].y<=b.y&&a.points[c].y>b.y,k=(a.points[f].x-a.points[c].x)*(b.y-a.points[c].y)/(a.points[f].y-a.points[c].y)+a.points[c].x;if((a.points[c].y<=b.y&&a.points[f].y>b.y||j)&&b.x<k)e=1-e}return 1===e};Board.snapPoly=function(a){var b=Board.getPolySnapXY(a);null!=b&&Board.translatePoly(a,b)};
Board.getPolySnapXY=function(a){for(var b,d=Math.max(Board.width,Board.height),e=a.points.length,c=e-1,f=0;f<e;c=f,++f){c=a.points[c];for(var j=a.points[f],k=Board.polyform.polys.length,l=0;l<k;++l){var h=Board.polyform.polys[l];if(a.name!=h.name)for(var m=h.points.length,g=m-1,i=0;i<m;g=i,++i){g=Board.getSnapXY(c,j,h.points[g],h.points[i]);if(null!=g){var n=Math.lengthXY(g);if(n<d){d=n;b=g}}}}}return d<9?b:null};
Board.getSnapXY=function(a,b,d,e){var c={x:b.x-a.x,y:b.y-a.y},f={x:e.x-d.x,y:e.y-d.y};if(Math.liesInXY(a,b,d,e)&&Math.areParallelXY(c,f)){b=Math.dotXY({x:d.x-a.x,y:d.y-a.y},c)/Math.dotXY(c,c);c={x:b*c.x,y:b*c.y};a={x:a.x+c.x,y:a.y+c.y};return{x:d.x-a.x,y:d.y-a.y}}return null};
Board.validatePolyform=function(){YAHOO.util.Connect.asyncRequest("POST","/api/valid",{success:function(a){Board.stopPuzzling();Board.validateCallback&&Board.validateCallback(a)},failure:function(){},argument:[Board.polyform.id]},"polyform="+JSON.stringify(Board.polyform))};